#INCLUDE <16F887.H>
#FUSES HS
#USE DELAY (CLOCK = 20M)

#DEFINE UP PIN_B0
#DEFINE DW PIN_B1
#DEFINE START_STOP PIN_B2
#DEFINE ENABLE PIN_C7

#DEFINE SER PIN_D0
#DEFINE SCK PIN_D1
#DEFINE RCK PIN_D2

UNSIGNED INT16 VALUE, CAPTOCDO;
INT1 TTDC;

VOID XUAT_1BYTE(UNSIGNED INT8 BYTEXUAT)
{
   UNSIGNED INT8 I;
   # BIT BSER = BYTEXUAT.7;
   FOR (I=0;I<8;I++)
   {
      OUTPUT_BIT (SER,BSER);
      OUTPUT_LOW (SCK);
      OUTPUT_HIGH(SCK);
      BYTEXUAT = BYTEXUAT <<1;
   }
}
VOID XUATLED7DOAN (UNSIGNED INT8 LED2, LED1)
{
   XUAT_1BYTE(LED2);
   XUAT_1BYTE(LED1);
   OUTPUT_LOW(RCK);
   OUTPUT_HIGH(RCK);
}

UNSIGNED INT8 MA7DOAN[10]={0XC0, 0XF9, 0XA4, 0XB0, 0X99, 0X92, 0X82, 0XF8, 0X80, 0X90};

VOID KT_START_STOP()
{
   IF (INPUT(START_STOP)==0)
   {
      DELAY_MS(20);
      IF (INPUT(START_STOP)==0)
      {  
         WHILE (INPUT(START_STOP)==0){}
         TTDC=~TTDC;
         IF (TTDC==1)
            CAPTOCDO=1;
         ELSE
            CAPTOCDO=0;
         XUATLED7DOAN(MA7DOAN[CAPTOCDO/10],MA7DOAN[CAPTOCDO%10]);
      }
   }
}
VOID KT_UP()
{
   IF (INPUT(UP)==0)
   {
      DELAY_MS(20);
      IF (INPUT(UP)==0)
      {  
         WHILE (INPUT(UP)==0){}
         CAPTOCDO++;
         IF (CAPTOCDO>10)
            CAPTOCDO=10;
         XUATLED7DOAN(MA7DOAN[CAPTOCDO/10],MA7DOAN[CAPTOCDO%10]);
      }
   }
}
VOID KT_DW()
{
   IF (INPUT(DW)==0)
   {
      DELAY_MS(20);
      IF (INPUT(DW)==0)
      {  
         WHILE (INPUT(DW)==0){}
         CAPTOCDO--;
         IF (CAPTOCDO<1)
            CAPTOCDO=1;
         XUATLED7DOAN(MA7DOAN[CAPTOCDO/10],MA7DOAN[CAPTOCDO%10]);
      }
   }
}
VOID MAIN()
{
   SET_TRIS_C(0);
   SET_TRIS_D(0);
   SET_TRIS_B(0XFF);
   OUTPUT_LOW(PIN_C3);
   SETUP_CCP1(CCP_PWM);
   SETUP_TIMER_2(T2_DIV_BY_16,249,1);
   SET_TIMER2(0);
   OUTPUT_HIGH(ENABLE);
   VALUE = 0;
   TTDC = 0;
   CAPTOCDO = 0;
   SET_PWM1_DUTY(VALUE);
   XUATLED7DOAN(MA7DOAN[CAPTOCDO/10],MA7DOAN[CAPTOCDO%10]);
   WHILE (TRUE)
   {  
      IF (TTDC == 1)
      {
         KT_UP();
         KT_DW();
      }
      KT_START_STOP();
      VALUE = CAPTOCDO * 100;
      SET_PWM1_DUTY(VALUE);
   }
}
