#INCLUDE <16F887.H>
#DEVICE ADC = 10
#FUSES HS
#USE DELAY (CLOCK = 20M)

#DEFINE LCD_ENABLE_PIN PIN_E2
#DEFINE LCD_RS_PIN PIN_E0
#DEFINE LCD_RW_PIN PIN_E1
#DEFINE LCD_DATA4 PIN_D4
#DEFINE LCD_DATA5 PIN_D5
#DEFINE LCD_DATA6 PIN_D6
#DEFINE LCD_DATA7 PIN_D7
#INCLUDE <LCD.C>

UNSIGNED INT16 ND1;

VOID MAIN ()
{
   SET_TRIS_D(0);
   SET_TRIS_E(0);
   LCD_INIT();
   LCD_GOTOXY(5,1);
   LCD_PUTC("DO NHIET DO");
   SETUP_ADC(ADC_CLOCK_DIV_2);
   SETUP_ADC_PORTS(SAN0|VSS_VDD);
LAP:
   SET_ADC_CHANNEL(0);
   DELAY_US(10);
   ND1 = READ_ADC()/2.046;
   LCD_GOTOXY(1,2);
   PRINTF(LCD_PUTC,"TEMP=%02LU C", ND1);
   LCD_GOTOXY(8,2);
   LCD_PUTC(0XDF);
   IF (ND1>35)
   {
         LCD_GOTOXY(1,2);
         PRINTF(LCD_PUTC,"CANH BAO QUA NHIET");
         DELAY_MS(300);
         LCD_GOTOXY(1,2);
         PRINTF(LCD_PUTC,"                  ");
         DELAY_MS(300);
   }
   GOTO LAP;
 }
   


