#INCLUDE <16F887.H>
#FUSES HS
#DEVICE ADC=10
#USE DELAY(CLOCK=20M)
#USE RS232(BAUD=9600, XMIT=PIN_C6, RCV=PIN_C7)

#DEFINE LCD_ENABLE_PIN  PIN_E2
#DEFINE LCD_RS_PIN      PIN_E0
#DEFINE LCD_RW_PIN      PIN_E1

#DEFINE LCD_DATA4       PIN_D4
#DEFINE LCD_DATA5       PIN_D5
#DEFINE LCD_DATA6       PIN_D6
#DEFINE LCD_DATA7       PIN_D7

#INCLUDE <LCD.C>

UNSIGNED INT8 RCV_DATA;
UNSIGNED INT16 ND1;

#INT_RDA

VOID RECEIVED_DATA()
{  
   RCV_DATA=GETC();
   LCD_GOTOXY(5,2);
   PRINTF(LCD_PUTC,"TEMP=%02U C",RCV_DATA);
   LCD_GOTOXY(12,2);
   LCD_PUTC(0XDF);  
   DELAY_MS(10);
}

VOID MAIN()
{  
   SET_TRIS_D(0X00);
   SET_TRIS_E(0X00);
   LCD_INIT();
   ENABLE_INTERRUPTS(GLOBAL);
   ENABLE_INTERRUPTS(INT_RDA);
   SETUP_ADC(ADC_CLOCK_DIV_2);
   SETUP_ADC_PORTS(SAN0|VSS_VDD);
LAP: 
   SET_ADC_CHANNEL(0);
   DELAY_MS(10);  
   ND1=READ_ADC();
   ND1=ND1/2.046;
   LCD_GOTOXY(5,1);
   PRINTF(LCD_PUTC,"TEMP=%02LU C",ND1);
   LCD_GOTOXY(12,1);
   LCD_PUTC(0XDF);
GOTO LAP; 
}
